package compiladores1.Models;

/**
 *
 * @author jmong
 */
public enum TokenType {
    ABSOLUTE, DOWNTO, BEGIN, DESTRUCTOR, MOD,
    AND, ELSE, CASE, EXTERNAL, NOT,
    ARRAY, END, CONST, DIV, PACKED,
    ASM, FILE, CONSTRUCTOR, DO, PROCEDURE,
    FOR, FORWARD, FUNCTION, GOTO, RECORD,
    IF, IN, OR, PRIVATE, UNTIL,
    PROGRAM, REPEAT, STRING, THEN, VAR,
    WHILE, XOR, WITH, TYPE, OF,
    USES, SET, OBJECT, TO,IDENTIFIER,
    WRITE, WRITELN,
    NUMBER, SYMBOL, UNKNOWN, CHAR_CODE
}